### PR TITLE
Adapt to the current Qabel Core version

### PR DESCRIPTION
**Pull request by jasinai**
Updates the module to the current Qabel-Core version.
For now it works like before, more functionality is not implemented.

### CODE REVIEW

**Comment by thechauffeur** [comment]
Is this PR still up to date @jasinai?

**Comment by thechauffeur** [comment]
I guess this will this be done by #3 when porting to ackack is finished, right? And again the question, is this is still up to date?

**Comment by thechauffeur** [comment]
@Gottox and @jasinai please discuss if this should be merged, updated or closed.

**Comment by jasinai** [comment]
Closed, because #3 is more up to date.

**Pull request closed without merging**
